#!/bin/bash
# Run this file to generate regridded runoff data

for dir in mom*
do
  echo "cd $dir/grids; bash README"
  (cd $dir/grids; bash README)
done
for dir in mom*/RYF????/
do
  echo "cd $dir; bash README"
  (cd $dir; bash README)
done

md5sum mom*/RYF*/runoff_regrid.nc > md5sum.txt

