#!/bin/bash

DATADIR=/g/data1/ua8/MOM/grids/01/
MOSAICDIR=${DATADIR}/mosaic
TOPOGDIR=${DATADIR}/topog/KDS75

ln -sf ${MOSAICDIR}/grid_spec.nc .
ln -sf ${MOSAICDIR}/ocean_hgrid.nc .
ln -sf ${MOSAICDIR}/ocean_mosaic.nc .
ln -sf ${TOPOGDIR}/topog.nc .      

md5sum *.nc > md5sum.txt
