#!/bin/bash

MOSAICDIR=/short/v45/aph502/mom/input/mom025/mosaic
TOPOGDIR=/short/v45/aph502/mom/input/mom025/levels_50

cp ${MOSAICDIR}/grid_spec.nc .
cp ${MOSAICDIR}/ocean_hgrid.nc .
cp ${MOSAICDIR}/ocean_mosaic.nc .
cp ${TOPOGDIR}/topog.nc .      

md5sum *.nc > md5sum.txt

